/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package avaliacaogerenciamentolivros;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    
    public boolean tecnologia, ficcao, romance, historia; 
    public String tipo, situacaoLeitura;
    private int linhaEdicao = -1; 
    private List<Livro> listaLivros; 
    private Arquivo arquivo; 
    
    public Interface() {
        initComponents();
        arquivo = new Arquivo("Livros");
        listaLivros = arquivo.leArquivo();
        carregarTabela();
    }
    
    public void carregarTabela(){
        DefaultTableModel tabela = (DefaultTableModel) tblLivros.getModel();
        
        for(Livro l : listaLivros){
            tabela.addRow(l.obterDados()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntGroupTipo = new javax.swing.ButtonGroup();
        btnGroupSituacao = new javax.swing.ButtonGroup();
        lblTextoInicial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdo_fisico = new javax.swing.JRadioButton();
        rdo_digital = new javax.swing.JRadioButton();
        txtAutor = new javax.swing.JTextField();
        txtAnoPublicacao = new javax.swing.JTextField();
        chkTecnologia = new javax.swing.JCheckBox();
        chkFiccao = new javax.swing.JCheckBox();
        chkRomance = new javax.swing.JCheckBox();
        chkHistoria = new javax.swing.JCheckBox();
        rdo_iniciada = new javax.swing.JRadioButton();
        rdo_em_andamento = new javax.swing.JRadioButton();
        rdo_concluido = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTextoInicial.setText("Cadastramento de Livros");

        jLabel1.setText("Titulo:");

        jLabel2.setText("Autor:");

        jLabel3.setText("Ano Publicação:");

        jLabel4.setText("Tipo:");

        jLabel5.setText("Categoria:");

        jLabel6.setText("Situação de Leitura:");

        bntGroupTipo.add(rdo_fisico);
        rdo_fisico.setText("Fisico");

        bntGroupTipo.add(rdo_digital);
        rdo_digital.setText("Digital");

        chkTecnologia.setText("Tecnologia");

        chkFiccao.setText("Ficção");

        chkRomance.setText("Romance");

        chkHistoria.setText("Historia");

        btnGroupSituacao.add(rdo_iniciada);
        rdo_iniciada.setText("Iniciada");

        btnGroupSituacao.add(rdo_em_andamento);
        rdo_em_andamento.setText("Em Andamento");

        btnGroupSituacao.add(rdo_concluido);
        rdo_concluido.setText("Concluido");

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Autor", "Ano Publicação", "Tipo", "Categoria", "Situação de Leitura"
            }
        ));
        jScrollPane1.setViewportView(tblLivros);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTextoInicial)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAutor)
                            .addComponent(txtTitulo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_fisico)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_digital))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkTecnologia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkFiccao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkRomance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkHistoria))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdo_iniciada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_em_andamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_concluido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(rdo_fisico)
                    .addComponent(rdo_digital))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTecnologia)
                    .addComponent(chkFiccao)
                    .addComponent(chkRomance)
                    .addComponent(chkHistoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_iniciada)
                    .addComponent(rdo_em_andamento)
                    .addComponent(rdo_concluido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        tecnologia = chkTecnologia.isSelected(); 
        ficcao = chkFiccao.isSelected(); 
        romance = chkRomance.isSelected(); 
        historia = chkHistoria.isSelected(); 
        
        JOptionPane.showMessageDialog(null, "Tecnologia: "+tecnologia+
                "\nFicção: "+ficcao+
                "\nRomance: "+romance+
                "\nHistória: "+historia, "Alerta", JOptionPane.INFORMATION_MESSAGE); 
        
        if(rdo_fisico.isSelected()){
            tipo = "Físico"; 
        } else if(rdo_digital.isSelected()) {
            tipo = "Digital"; 
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um tipo", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        if(rdo_iniciada.isSelected()){
            situacaoLeitura = "Iniciada"; 
        } else if (rdo_em_andamento.isSelected()){
            situacaoLeitura = "Em andamento"; 
        } else if (rdo_concluido.isSelected()){
            situacaoLeitura = "Concluída"; 
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma situação de leitura", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        Livro livro = new Livro(txtTitulo.getText(), txtAutor.getText(), txtAnoPublicacao.getText(), tipo, situacaoLeitura); 
        
        DefaultTableModel tabela = (DefaultTableModel) tblLivros.getModel();
        tabela.addRow(livro.obterDados());
        
        if(linhaEdicao == -1){
            listaLivros.add(livro);
        } else {
            listaLivros.set(linhaEdicao, livro); 
            linhaEdicao = -1; 
        }
        
        arquivo.gravaArquivo();
        carregarTabela();
        JOptionPane.showMessageDialog(
                null,
                "Dados salvos com sucesso!"
        );
        
        System.out.println("Livro adicionado");
        for(Livro l : listaLivros){
            System.out.println(l);
        }
        
        txtAutor.setText(" "); 
        txtTitulo.setText(" ");
        txtAnoPublicacao.setText(" ");
        chkTecnologia.setSelected(false);
        chkRomance.setSelected(false);
        chkHistoria.setSelected(false);
        chkFiccao.setSelected(false); 
        btnGroupSituacao.clearSelection();
        bntGroupTipo.clearSelection();        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        int linha = tblLivros.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(
                    null,
                    "Selecione um livro para editar"
            );
            return;
        }
        
        linhaEdicao = linha;
        Livro l = listaLivros.get(linha);
        txtTitulo.setText(l.titulo);
        txtAutor.setText(l.autor);
        txtAnoPublicacao.setText(l.anoPublicacao);
        
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bntGroupTipo;
    private javax.swing.JButton btnEditar;
    private javax.swing.ButtonGroup btnGroupSituacao;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkFiccao;
    private javax.swing.JCheckBox chkHistoria;
    private javax.swing.JCheckBox chkRomance;
    private javax.swing.JCheckBox chkTecnologia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTextoInicial;
    private javax.swing.JRadioButton rdo_concluido;
    private javax.swing.JRadioButton rdo_digital;
    private javax.swing.JRadioButton rdo_em_andamento;
    private javax.swing.JRadioButton rdo_fisico;
    private javax.swing.JRadioButton rdo_iniciada;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtAnoPublicacao;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
